---
# This playbook installs the test application for Relay42.
- hosts: localhost

  
  tasks:

  - include_vars: group_vars/vars.yml

  - git:
      repo: 'https://github.com/lc-nyovchev/opstest.git'
      dest: ~/relay42-optest

  - template:
      src: ~/relay42-optest/src/main/resources/application.properties
      dest: /tmp/application.properties
      owner: vlopez
      group: staff
      mode: 0644

  - lineinfile:
      path: /tmp/application.properties
      regexp: '^suchname='
      line: 'suchname="{{username}}"'

